pipeline {
    agent {
        docker { image 'oraclelinux:7-slim' }
    }
    stages {
        stage('Checkout'){
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh 'mkdir /scratch'
                sh 'yum install -y git bc unzip tar wget which sendmail zip java-1.8.0-openjdk-devel && rm -rf /var/cache/yum'
                sh 'wget http://redrockdigimark.com/apachemirror/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz'
                sh 'tar -xvzf apache-maven-3.5.2-bin.tar.gz -C /scratch/mvn'
                sh '/scratch/mvn -version'
            }
        }
    }
}
