#!groovy

pipeline {
    agent {
        docker { image 'maven:3.5.3-jdk-8-slim' }
    }
    stages {
        stage('Checkout'){
            steps {
                checkout scm
            }
        }

        stage('BuildMQ') {
            steps {
                git url: 'https://github.com/eclipse-ee4j/openmq.git'
                sh 'cd mq/src/buildcfg/tools/ri/fscontext; jar cf fscontext.jar -C fscontext_jar .'
                sh 'cd mq/src/share/help; jar cf helpfiles.zip -C helpfiles .'
                sh 'mvn --version'
                sh 'mvn -f mq/pom.xml clean install'
            }
        }  
        
/*
        stage('BackupMQBits') {
            steps {
                stash includes: 'mq/dist/bundles/mq*.zip', name: 'zips'
            }
        }
        
        stage('CheckoutTests') {
            steps {
            }
        }
*/
        
        stage('RunJMSDevTests') {
            steps {
//                unstash 'zips'
                git url: 'https://github.com/yaminikb/openmq-tools.git'
                git url: 'https://github.com/javaee/glassfish.git'
                env.PATH = "${tool 'ant-newest'}/bin:${env.PATH}"
                sh "chmod +x ${env.WORKSPACE}/scripts/jms-dev-tests.sh"
                sh "${env.WORKSPACE}/scripts/jms-dev-tests.sh"
            }
        }
    }
}


